language: node_js
node_js:
 - "stable"
cache: 
  directories: 
    - "node_modules" 
install:
  - npm install   
 
services: 
   - mongodb 

env: 
   global: 
   - NODE_ENV=development

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: 
   - npm run test



 
 
