language: node_js
node_js:
 - "stable"
cache: 
  directories: 
    - "node_modules" 
install:
  - npm install   
 
services: 
   - mongodb 

env: 
   global: 
   - NODE_ENV=development

script: 
   - npm run test



 
 
